config/routes.rb
Rails.application.routes.draw do
  resources :home
  devise_for :users
  resources :trips do
    resources :comments
  end
  resources :trip_users
  resources :users do
    resources :references
  end

   root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :trip
  belongs_to :user
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient_id, class_name: "User"
end

app/models/trip.rb
class Trip < ActiveRecord::Base
	has_many :trip_users
	has_many :comments
	has_many :users, through: :trip_users
	belongs_to :organizer, class_name: "User", foreign_key: :organizer_id, inverse_of: :trips_organized
	after_save :organizer_added
	geocoded_by :meeting_point
	after_validation :geocode, :if => :meeting_point_changed?

	def organizer_added
		if TripUser.where(trip: self, user: self.organizer).first == nil
			self.organizer.trip_users.create(trip:self)
		end
	end

end

app/models/trip_user.rb
class TripUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :email, :case_sensitive => false
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :trip_users
  has_many :comments

  has_many :references
  has_many :referencers, through: :references

  has_many :trips_organized, class_name: "Trip", foreign_key: :organizer_id, inverse_of: :organizer
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "160x160>", :tiny => "75x75>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  # Is this secure?
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :nickname, :education, :about, :occupation, :hometown, :interests, :past_homes, :past_travels, :future_travels, :travel_style, :location, :age, :currently_traveling, :avatar) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  # def configure_permitted_parameters
  # 	devise_parameter_sanitizer.for(:sign_up) << :username
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comments = Comment.where(trip_id: params[:id])
	end

	def create
		@trip = Trip.where(id: params[:trip_id]).first
		@comment = @trip.comments.new(comment_params)
		@comment.user = current_user
		if @comment.save
			redirect_to trip_path(id: params[:trip_id])
		else
			raise params.inspect
		end
	end

	def destroy
		@trip = Trip.where(id: params[:trip_id]).first
		@comment = @trip.comments.find(params[:id])
		@comment.destroy
		redirect_to trip_path(@trip)
	end

	private
	def comment_params
		params.require(:comment).permit(:trip_id, :user_id, :body)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
	def index
		@references = Reference.where(recipient_id: params[:id])
		raise params.inspect
	end
	def show
		@user = User.where(id: params[:id]).first
		@references = @user.references.all
		# @theseReferences = Reference.where(user = User.last)
	end

	def new
		@references.new
	end

	def create
		@user = current_user
		@reference = @user.references.new(reference_params)
		@reference.recipient_id = User.where(id: params[:user_id]).first
		if @reference.save && @reference.recipient_id != nil
			redirect_to user_path(id: params[:user_id])
		else
			raise params.inspect
		end
	end

	def destroy
		@user = User.where(id: params[:user_id]).first
		@reference = @user.references.find(params[:id])
		@reference.destroy
		redirect_to user_path(@user)
	end
	private
	def reference_params
		params.require(:reference).permit(:rating, :user_id, :description, :recipient_id)
	end
end

app/controllers/trip_users_controller.rb
class TripUsersController < ApplicationController
	def update
		@trip = Trip.where(id: params[:id]).first

		user_added = current_user.trip_users.create(trip: @trip)
		if user_added.save
			redirect_to trip_path(id: params[:id])
		end
	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	def index

		if params[:search].present?
			@trips = Trip.near(params[:search], 30).reorder(day: :asc)
			@placeName = params[:search]
		else
			@trips = Trip.near("losangeles", 70).reorder(day: :asc)
			@placeName = "Los Angeles, California"
		end

	end
	def show
		@trip = Trip.where(id: params[:id]).first
		@comments = @trip.comments.all
		@tripLat = @trip.latitude
		@tripLon = @trip.longitude
		
	end
	def new
		@user = current_user
		@trip = @user.trips_organized.new
	end
	def create
		@user = current_user
		@trip = @user.trips_organized.new(trip_params)
		if @trip.save
			redirect_to trips_path
		else
			raise params.inspect
		end
	end

	
	private
	def trip_params
		params.require(:trip).permit(:title, :organizer_id, :description, :day, :departure_time, :price, :duration, :size, :require_rating, :latitude, :longitude, :meeting_point)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end

	def create
		@user = current_user
		@reference = @user.references.new(reference_params)
		@reference.recipient_id = User.where(id: params[:id]).first
		if @reference.save && @reference.recipient_id != nil
			redirect_to user_path(id: params[:id])
		else
			raise params.inspect
		end
	end


	def show
		@references = Reference.where(recipient_id: params[:id])
		@user = User.where(id: params[:id]).first
	end

	

	private
	def reference_params
		params.require(:reference).permit(:rating, :user_id, :description, :recipient_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/trip_users_helper.rb
module TripUsersHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_index.html.erb
<%# @comments.each do |c| %>
<%#= c.comment %>
<%# end %>

<%#= @post.comments.each do |c| %>
	<%#= comment.body %>
<%# end %>	

app/views/comments/_new.html.erb
<%= form_for ([@trip, @trip.comments.build]) do |f| %>
	<%= f.text_area :body, placeholder: "Enter your question or comment!" %>
	<%= f.submit 'Add a comment' %>
<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
	<div class="container">
		<div class="center">
			<div class="titleHolder">
				<h1>Meet up with other travelers <br>for independently planned day trips</h1>
				<div class="searchBox">
						<%= form_tag trips_path, :method => :get do %>
							<%= text_field_tag :search, params[:search], :placeholder => "Search your location" %>
							<%= submit_tag "Search", :name => nil %>
						<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="homeBody">
	<div class="container">
		<div class="midHomeRow">
			<div class="row">
				<h1>How it works:</h1>
			</div>
			<div class="row">
				<div class="oneThird">
					<div class="howToBox">
						<div class="topRow">
							<h1><%= image_tag("search.png", :alt=> "search") %></h1>
						</div>
						<div class="titleRow">
							<h3>1. Search for Trips</h3>
						</div>
						<div class="bodyRow">
							<p>Search the city in which you're currently traveling, or search where you will be soon. Plans change, so Gather is meant to be used last-minute.</p>
						</div>
					</div>
				</div>
				<div class="oneThird">
					<div class="howToBox">
						<div class="topRow">
							<h1><%= image_tag("personadd.png", :alt=> "add yourself") %></h1>
						</div>
						<div class="titleRow">
							<h3>2. Join a trip that looks fun</h3>
						</div>
						<div class="bodyRow">
							<p>Whether it's sharing a rental car, going on an organized tour, or joining a pub crawl, find something that interests you.</p>
						</div>
					</div>
				</div>
				<div class="oneThird">
					<div class="howToBox">
						<div class="topRow">
							<h1><%= image_tag('gotravel.png', :alt=>'go travel!') %></h1>
						</div>
						<div class="titleRow">
							<h3>3. Go Travel!</h3>
						</div>
						<div class="bodyRow">
							<p>Make new friends and save money! Be at the designated meeting point at the set time, and travel from there!</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="homeBodyDark">
	<div class="container">

		<div class="row">
			<div class="oneThird">
				<ul>
					<li>About Gather</li>
				</ul>
			</div>
						<div class="oneThird">
				<ul>
					<li>Legal / Privacy</li>
				</ul>
			</div>
						<div class="oneThird">
				<ul>
					<li><a href="http://www.danielmontgomery.com">Contact Us</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
	  <script type="text/javascript"
	      src='https://maps.googleapis.com/maps/api/js?key='+ENV["google_api_key"]>
	  </script>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div id="navbar">
	<div class="container">
		<div class="logo"><%= link_to "Gather", home_index_path, :class => "linkTitle" %></div>
		<div id="nav-collapse">MENU</div>
		<nav class="nope">
			<ul>
				<li><%= link_to "Trips", trips_path, :class => "link" %></li>
				<% if current_user == nil %>
				<li><%= link_to "Sign up", new_user_registration_path, :class => "link" %> / <%= link_to "Login", new_user_session_path, :class => "link" %></li>
				<% else %>
				<li><%= link_to "Profile", user_path(current_user.id), :class => "link" %></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "link" %></li>
				<% end %>
			</ul>	
		
		</nav>
	</div>
</div>
<%= yield %>
	<script>
	$( '#nav-collapse').click(function() {
	  	$('nav').toggleClass("nope", 2000);
	});
	</script>
</body>
</html>

app/views/references/_form.html.erb
<%= form_for ([@reference, @user.references.build]) do |f| %>
	Rating: (Good or Bad, 1 is bad, 2 is good)<%#= f.select :rating, options_for_select(%w[1 2]) %>
	Text<%= f.text_area :description, placeholder: "Add a reference for this user. Be nice!" %>
	<%= f.submit 'Save Reference' %>
<% end %>

app/views/references/_references.html.erb
<div class="references">
	<% if @references != nil %>
		<% @references.each do |r| %>
		<div class="referenceHolder">
			<div class="refImage">
				<% if !r.user.avatar.url.nil? %>
					<%= image_tag r.user.avatar.url(:thumb) %>
				<% else %>
					<%= image_tag 'missing.png' %>
				<% end %>
			</div>
			<div class="referenceField">
				<b><%= link_to r.user.first_name, user_path(r.user.id) %></b><br>
				<%= r.description %><br>
			</div>
<!--             <%# if r.user == current_user %>
            	<div class="deleteButton">
            	      <%#= link_to "Delete", [r.recipient_id, r], method: :delete, data: { confirm: "Are you sure?" } %>
      	        </div>
            <%# end %>	 -->		
		</div>
		<% end %> 
	<% else %>
		<p>There are no references yet, add one!</p>
	<% end %>
</div>

app/views/trip_users/new.html.erb
<p>Add a new trip.</p>
<p>This is your trip_users_path</p>

<% form_for trip_user.new do |f| %>
	<%= f.text_field :title %>
	<%= f.submit "add a new trip with this title" %>
<% end %>	

app/views/trips/index.html.erb
<head>
	<script type="text/javascript">
	//cycle through markers:
      function initialize() {
      	var i = 0;
		// for(i = 0; i < @trips.length; i++) {
		// 	var data = @trips[i];
		// 	var myLatLng = new google.maps.latLng(data.latitude, data.longitude);
		// 	var title = data.title;
		// };
		var markers = [
			<% if @trips.length != 0 %>
				<% for i in 0...@trips.length do %>
				{
					lat: <%= @trips[i].latitude %>,
					lng: <%= @trips[i].longitude %>,
					name: "<%= @trips[i].title %>"
				},
				<% end %>
				
			<% else %>
				{
					lat: 34.0337,
					lng: -118.754,
					name: "Smog City!"
				},
			<% end %>
			];
		var infowindow = new google.maps.InfoWindow({
			maxWidth: 300
		});
		var first = markers[0];
		var myLatLng = new google.maps.LatLng(first.lat, first.lng);
        var mapOptions = {
          zoom: 11,
          center: myLatLng
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
        for (i = 0; i < markers.length; i++) {
        	var data = markers[i];
        	var myLatLng = new google.maps.LatLng(data.lat, data.lng);
        	var marker = new google.maps.Marker({
        		position: myLatLng,
        		map: map,
        		title: data.title
        	});
        	google.maps.event.addListener(marker, 'click', function(marker, name) {
        		return function() {
        			infowindow.setContent(name);
        			infowindow.open(map,marker);
        		};
        	}(marker, data.name));
        }
      }//end marker loop
      console.log("map loaded");
      google.maps.event.addDomListener(window, 'load', initialize);
 
   	</script>
</head>
<div class="container">
	<h1>Search for trips</h1>
	<br>
	<% if current_user != nil %>
		<p><%= link_to 'Make a new trip', new_trip_path, :class => "link_inline" %> or search for one below:</p>
	<% else %>
		<p> You must be logged in to create or join a trip! <%= link_to "Sign up", new_user_registration_path, :class => "link_inline" %> or <%= link_to "Login", new_user_session_path, :class => "link_inline" %> today! </p>
	<% end %>
	<br>
	<div class="searching">
		<%= form_tag trips_path, :method => :get do %>
			<%= text_field_tag :search, params[:search], :placeholder => "Enter your location" %>
			<%= submit_tag "Search", :name => nil %>
		<% end %>
	</div>
	<br>
	<% if @trips.length != 0 %>
		<h3>Here are the closest trips happening soon near <%= @placeName %>!</h3><br>
		<div id="map-canvas"></div>
	<% else %>
		<h3>Unfortunately there are no trips in your area. Start one!</h3>
	<% end %>
	<% @trips.each do |t| %>
		<div class="result">
			<div class="left-col">
				<div class="price">
					<div class="priceTop">
						<h1><span class="dollar">$</span><%= t.price %></h1>
					</div>
					<div class="priceBottom">
						<p>Expected</p>
					</div>
				</div>
			</div>
			<div class="mid-col">
				<b><span class="tripTitle"><%= link_to t.title, t %></span></b><br>
				<span class="lighten">Organized by</span> <%= link_to t.organizer.first_name, t %> <%= link_to t.organizer.last_name, user_path(t.organizer.id) %><br>
				<span class="lighten">Participants: </span><% t.users.each do |u| %>
									<%= link_to u.first_name, user_path(u.id) %>,
								<% end %>
			</div>
 			<div class="right-col">
				<p><%= t.day.to_formatted_s(:long) %></p>
			</div> 
		</div>	
	<% end %>
</div>

app/views/trips/new.html.erb
<div class="container">
	<div class="centerer"><h1>Add a new trip</h1></div>
	<br>

	<%= form_for @trip do |f| %>
		Trip title: <%= f.text_field :title %><br>
		Description: <%= f.text_area :description %><br>
		Date: <%= f.date_field :day %><br>
		Departure Time: <%= f.time_field :departure_time %><br>
		Expected Price: $<%= f.number_field :price %><br>
		Duration: <%= f.text_field :duration %><br>
		Max Number of People: <%= f.number_field :size %><br>
		<!-- Required User Reliability Rating:  --><%#= f.number_field :require_rating %><br>
		Meeting Point: <%= f.text_field :meeting_point %><br>
		<%= f.submit "Add a new trip with this title" %>
	<% end %>	
</div>

app/views/trips/show.html.erb
<head>

  <script type="text/javascript">
      function initialize() {
        var myLatLng = new google.maps.LatLng(<%= @tripLat %>, <%= @tripLon %>)
        var mapOptions = {

          center: myLatLng,
          zoom: 15
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
        var marker = new google.maps.Marker({
        	position: myLatLng,
        	map: map,
        	title:"<%= @trip.meeting_point %>"
        });
      }
      console.log("map loaded");
      google.maps.event.addDomListener(window, 'load', initialize);
 
   </script>
</head>
<body>
	<div class="container">

    <!-- Left Column -->
    <div class="leftCol">
      <div class="spacedOut"><h3>Organizer:</h3></div>
      <div class="spacedOut"><%= image_tag @trip.organizer.avatar.url(:thumb) %>
        <%= link_to @trip.organizer.first_name, user_path(@trip.organizer.id) %> <%= link_to @trip.organizer.last_name, user_path(@trip.organizer.id) %><br></div>
      <div class="spacedOut"><span class="redButton"><%= link_to "Back to Search", trips_path %></span></div>
      <div class="spacedOut"><h3>Nearby Trips</h3></div>    
      <ul>
        <% for location in @trip.nearbys(20) %>
          <li><%= link_to location.title, location %> (<%= location.distance.round(2) %> miles)</li>
        <% end %>
      </ul>
      <div class="spacedOut"><h3>Participants</h3></div>
       <!-- This runs through the list of everyone going on the trip. -->
       <ul>
        <% @trip.users.each do |u| %>
          <li><%= link_to u.first_name, user_path(u.id) %></li>
        <% end %>
      </ul>
      <div class="spacedOut">
        <% if current_user != nil %>
        <%= link_to "Join this trip!", trip_user_path, method: :patch, :class => "blueButton" %>
        <% end %></div>
    </div>
    <!-- Right(Main) Column -->
    <div class="rightCol">
    	<h1><%= @trip.title %></h1><br>
      <h3>Departure Time: <%= @trip.departure_time.strftime("%H:%M%P") %></h3>
      <div class="row">
        <div class="twoThirds">
          <b>Description: <br></b><%= @trip.description %><br>
        </div>
        <div class="oneThird">
          <div class="priceBox">
            <div class="priceTop">
              <h1><span class="dollar">$</span><%= @trip.price %></h1>
            </div>
            <div class="priceBottom">
              <p>Expected</p>
            </div>
          </div>
          <div class="priceBox">
            <div class="priceTop">
              <h1><span class="dollar"></span><%= @trip.users.length %></h1>
            </div>
            <div class="priceBottom">
              <p>People Going</p>
            </div>
          </div>
        </div>
      </div>
      <br>
      <h2>Meeting Point:</h2> <h3><%= @trip.meeting_point %> </h3><br>
    	<div id="map-canvas"></div>
    	
<!--     	<b>Meeting Point: </b><%= @trip.meeting_point %><br>
 -->
      <!-- This is the comment section. --> 
      <br>
      <div class="comments">
        <br>
        <h3>Comments:</h3>
        <!-- This checks if a user is logged in. If so, it should allow them to see and post comments. -->
        <% if current_user != nil %>
          <!-- If there are no comments, only the "add comment" box is displayed with the code above this line. -->
          <!-- If there are comments, they are displayed. -->
          <div class="references">
            <% if @comments != nil %>
              <% @comments.each do |c| %>
                <div class="referenceHolder">
                  <div class="refImage">
                   <%= image_tag c.user.avatar.url(:thumb) %>
                  </div>
                  <div class="referenceField">
                    <b><%= link_to c.user.first_name, user_path(c.user.id) %></b><br><%= c.body %><br><br>
                  </div>
                  <!-- Users should only be able to delete their own comments. -->
                  <% if c.user == current_user %>
                  <div class="deleteButton">
                    <%= link_to "Delete", [c.trip, c], method: :delete, data: { confirm: "Are you sure?" } %>
                  </div>
                </div>
                <% end %>
              <!-- End comment loop -->
              <% end %>
            <!-- End comments != nil checker -->
          <% end %>
        <% else %>
          <p>Oh No! You're not logged in! Please <%= link_to "log in", new_user_session_path, :class => "linkInline" %> to view or add comments!</p>
        <!-- End current_user != nil checker -->
        <% end %> 
        </div>
        <div class="commentBox">
          <%= render '/comments/new' %>
        </div>
      </div>
     </div>
	</div>
</body>

app/views/users/_form.html.erb
<%= form_for ([@user, @user.references.build]) do |f| %>
	<!-- Rating: (Good or Bad, 1 is bad, 2 is good) --><%#= f.select :rating, options_for_select(%w[1 2]) %>
	<br>
	<%= f.text_area :description, placeholder: "Add a reference for this user, be nice!" %><br>
	<%= f.submit 'Save Reference' %>
<% end %>

app/views/users/index.html.erb
<p>users index</p>

app/views/users/new.html.erb
<p>Add a new trip.</p>
<p>This is your new_user_path</p>

<% form_for User.create do |f| %>
	asdfghjnm<%= f.text_field :title %>
	<%= f.submit "add a new trip with this title" %>
<% end %>	

app/views/users/show.html.erb
<div class="container">
	<!-- Left Column -->
	<div class="leftCol">
		<%= image_tag @user.avatar.url(:thumb) %><br>
<!-- 		<h2>Verifications</h2>
		<ul>
			<li>email</li>
			<li>facebook</li>
			<li>twitter</li>
		</ul> -->
		<br>
		<div class="row">
			<div class="infoBar">
				<div class="leftInfo">
					<div class="validationNum"><%= @user.trips_organized.count %></div>
					<div class="floatLeft">Trips</div>
				</div>
			</div>
			<div class="infoBar">
				<div class="leftInfo">
					<div class="validationNum"><%= @user.references.count %></div>
					<div class="floatLeft">References</div>
				</div>
			</div>
			<br>
			<% if @user.hometown != nil %>
				<h5>Hometown:<br></h5>
				<div class="profileAttribute"><%= @user.hometown %></div>
			<% end %><br>
			<% if @user.occupation != nil %>
				<h5>Occupation<br></h5>
				<div class="profileAttribute"><%= @user.occupation %></div>
			<% end %><br>
			<% if @user.travel_style != nil %>
				<h5>Travel Style <br></h5>
				<div class="profileAttribute"><%= @user.travel_style %></div>
			<% end %><br>
		</div>
	</div>
	<!-- Right Column -->
	<div class="rightCol">
		<h1><%= @user.first_name %> <%= @user.last_name %></h1>
		<% if @user.age != nil %>
			<h4><%= @user.age %> years old</h4>
		<% end %>
		<h3><%= @user.location %></h3>
		<br>
		<h3>About </h3>
		<div class="aboutSection">
			<h4>Bio:</h4>
			<% if @user.about != nil %>
				<div class="profileAttribute"><%= @user.about %></div>
			<% end %><br>

			<% if @user.interests != nil %>
				<h5>Interests<br></h5>
				<div class="profileAttribute"><%= @user.interests %></div>
			<% end %><br>
			<% if @user.education != nil %>
				<h5>Education<br></h5>
				<div class="profileAttribute"><%= @user.education %></div>
			<% end %><br>
			<% if @user.past_homes != nil %>
				<h5>Where have I've lived <br></h5>
				<div class="profileAttribute"><%= @user.past_homes %></div>
			<% end %><br>
			<% if @user.past_travels != nil %>
				<h5>Where I've traveled <br></h5>
				<div class="profileAttribute"><%= @user.past_travels %></div>
			<% end %><br>
			<% if @user.future_travels != nil %>
				<h5>Where I want to travel someday<br></h5>
				<div class="profileAttribute"><%= @user.future_travels %></div>
			<% end %><br>
		</div>
		<br>
		<div class="comments">
			<h3>References</h3>
				<%= render 'references/references' %><br><br>
	        <div class="commentBox">
				<%= render 'form' %>
			</div>
			<br>
		</div>
		<h2>Trips organized by <%= @user.first_name %></h2><br>
		<% if @user.trips_organized == [] %>
			<p><%= @user.first_name %> has not organized any trips!</p>
		<% else %>
			<% @user.trips_organized.each do |t| %>
				<div class="tripBox">
					<h4><%= link_to t.title, trip_path(t.id) %></h4>
					<p><%= t.description %></p>
				</div>
			<% end %>
		<% end %>
	</div>
</div>